services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xbot
    env_file:
      - .env
    restart: always
    ports:
      - 3333:3333
    networks:
      - lightformsdevops # Add api to the database network

networks:
  lightformsdevops:
    external: true
